public enum Commands {
    MSG_SEND, MSG_EDIT, MSG_DELETE, MSG_RESEND, MSG_VERIFY,
    POST_SEND, POST_EDIT, POST_DELETE, POST_RESEND, POST_REACTION_ADD, POST_REACTION_REMOVE, POST_LOAD,
    CHANNEL_GET, CHANNEL_MOVE, CHANNEL_STATUS,
    VOICE_CONNECT, VOICE_MOVE, VOICE_DISCONNECT, VOICE_RECONNECT
}
